apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name:  demopythonappdp
  
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: demopythonappdp
        version: v1
    
    spec:
      containers:
      - name: demopythonappcontainer
        image: alvinngcheecheng/demopythonapp
        imagePullPolicy: Always
        env:
          - name: SERVICE_VERSION
            value: v1
        ports:
        - containerPort: 6000
