apiVersion: extensions/v1beta1
kind: kind: Service
apiVersion: v1
metadata:
  name:  demopythonappsvc
spec:
  selector:
    app:  Selector Label
  type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080