apiVersion: autoscaling/v1
kind: HorizontalPodAutoScaler

metadata:
name: myapp-hpa
namespaceP: myspace
labels:
  name: myapp-hpa

spec:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 20
  scaleTargeRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: app-deploy
    
    # apply [ kubectl apply -f appscaker.yaml] before u can use it.