apiVersion: apps/v1
kind: Deployment

metadata:
  name:  db-deploy
  namespace: myspace
  labels:
    name:  db-deploy

spec:
  # number of instances
  replicas: 1
  selector: 
    matchLabels:
      name: mydb-pod
  template: 
    # the pod that i am going to deploy
    metadata:
      name: mydb_pod
      labels:
        name: mydb-pod
        
    spec:
      containers:
      - name: mydb-conatiner
        image: stackupiss/northwind-db:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306

---

apiVersion: v1
kind: Service

metadata:
name: mydb-svc
namespace: myspace
labels:
  name: mydb-svc
spec:
  type: NodePort
  selector: 
    name: mydb-pod
  ports:
  - port: 3306
    # targetport referring to containerport above in first section.
    targetPort: 3306
    # Run  [ kubectl apply -f db-deploy.yaml ] : 
    # successfully creating a nodeport to access newly node.
    # Delete Created Node and proceed to create Cluster IP
    # Do so by changing [ type ] to "ClusterIP"

    # Service Discovery:
    # <Service-name>.<namespace>.svc.cluster.local -> DNS
    # mydb-svc.myspace.svc .cluster.local 

