apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helloworld.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helloworld.name" . }}
    helm.sh/chart: {{ include "helloworld.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    version: {{ .Values.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helloworld.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      version: {{ .Values.version }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helloworld.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        version: {{ .Values.version }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /hello
              port: http
          